export { default as Routes } from './Routes'
export { default as App } from './App'
export { default as Projects } from './Projects'
export { default as NavBar } from './NavBar'
export { default as Resume } from './Resume'
